# Generated by Django 5.0.1 on 2024-01-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Campsite', max_length=255)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
