# Generated by Django 5.0.1 on 2024-01-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalSettings',
            new_name='SiteConfiguration',
        ),
    ]
