# Generated by Django 5.0.1 on 2024-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSG', '0002_rename_globalsettings_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
